spring:
  application:
    name: notification-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://factory-db.c5g4a4ekcfvb.ap-northeast-2.rds.amazonaws.com:3306/notification_db?sslMode=trust
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: ${SERVER_PORT:8084}